### ISSUE TITLE
Rename "Cmd_AddCommand_" to "Cmd_FindCommand"

### ISSUE THREAD

**Issue by vorhon** [twizre/lightning#13]

**Comment by win32re** [comment]
Cmd_AddCommand_ is just an internal function used for the actual Cmd_AddCommand function.
So, to add a client command, you should use [`GameEngine::Cmd_AddCommand`](https://github.com/twizre/lightning/blob/master/d3d9/base/GameEngine.cpp#L23), not [`Cmd_AddCommand_`](https://github.com/twizre/lightning/blob/master/d3d9/base/GameEngine.cpp#L21).

**Comment by vorhon** [comment]
Yes, whose real name is "Cmd_FindCommand", not "Cmd_AddCommand_" so I suggest renaming it to the real name. :>

**Comment by win32re** [comment]
Woops, didn't see the difference. I thought you were just removing the
underscore.

On Thursday, February 12, 2015, Pedro Martins <notifications@github.com>
wrote:
> Yes, whose real name is "Cmd_FindCommand", not "Cmd_AddCommand_" so I
suggest renaming it to the real name. :>
>
> —
> Reply to this email directly or view it on GitHub.<
https://ci3.googleusercontent.com/proxy/Q5V9Srfp5NM_-0aYNuQgFC6XNrVq3zXFeu3aJhiVRfxKKJ7LUHek-kuEdgEp0pQjpWKzXuO4t6SSqT-st0ZcZw8xi51bQjheZrQy2XGbPMOLpv3iXu_yGqBHob3JL7q0GMLnqvrDR0ZjvigrARGsdsK1IN5rag=s0-d-e1-ft#https://github.com/notifications/beacon/AH6jfPbzwbP5vlP5hS60MiDcmfPp-SI3ks5nrO10gaJpZM4DfOo8.gif
>

**Comment by win32re** [comment]
This file has some nice stuff:
https://github.com/eezstreet/JediKnightGalaxies/blob/master/Game/codemp/qcommon/cmd_pc.cpp

**Comment by win32re** [comment]
Fixed in commit d0f517c52.
